name: news_app
description: News app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  google_fonts: ^3.0.1
  dio: ^4.0.6
  logger: ^1.1.0
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.7
  flex_color_scheme: ^6.1.1
  ionicons: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16

flutter:
  uses-material-design: true

  assets:
    - assets/

# launcher icon
flutter_icons:
  android: true
  image_path: "assets/logo.png"

# native splash screen
flutter_native_splash:
  color: "#ffffff"
  color_dark: "#23272e"
  image: "assets/logo.png"
  android: true
  android_12:
    color: "#ffffff"
    image: "assets/logo.png"
    color_dark: "#23272e"
